- name: Ping Sample
  hosts: all
  tasks:
    - name: do ping
      action: ping
      register: result

    - name: report status
      debug: msg={{ result }} verbosity=0

    - name: do cmd
      shell: hostname
      register: result

    - name: report status
      debug: msg={{ result }} verbosity=0

    - name: do cmd
      shell: ping www.google.com -c 1
      register: result

    - name: report status
      debug: msg={{ result }} verbosity=0

