- name: Ping Sample
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: do ping
      action: ping
      register: result

    - name: report status
      debug: msg={{ result }} verbosity=0

    - name: do cmd
      shell: hostname
      register: result

    - name: report status
      debug: msg={{ result }} verbosity=0
