- name: Ping Sample
  hosts: all
  tasks:
    - name: do ping
      action: ping
      
    - name: do cmd
      shell: ls
      register: result

    - name: report status
      debug: msg={{ result.results[0].stdout_lines }} verbosity=0
