- name: Ping Sample
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: do ping
      action: ping
      
    - name: do cmd
      shell: ping www.google.com -c 1
      register: result

    - name: report status
      debug: msg={{ result }} verbosity=0
